"use client";
import { ChangeEvent,useEffect,useState } from 'react';
import { Calculator, Download, Search, Save, SlidersHorizontal, Truck, Upload } from 'lucide-react';
import AppShell from './AppShell';
import { api,money } from '@/lib/api';

type FinancialSettings={taxPercent:number;advertisingPercent:number;marketplaceCommissionFallbackPercent:number;payoutDelayDays:number;payoutSchedule:string;payoutServiceFeePercent:number;urgentWithdrawalFeePercent:number};

export default function CostsClient(){
 const [rows,setRows]=useState<any[]>([]); const [q,setQ]=useState(''); const [dirty,setDirty]=useState<Record<string,any>>({}); const [saving,setSaving]=useState(false);const [rowsLoading,setRowsLoading]=useState(true);const [rowsError,setRowsError]=useState('');
 const [supplies,setSupplies]=useState<any[]>([]);const [supplyCosts,setSupplyCosts]=useState<Record<string,string>>({});const [savingSupply,setSavingSupply]=useState('');const [suppliesLoading,setSuppliesLoading]=useState(true);const [suppliesError,setSuppliesError]=useState('');
 const [settings,setSettings]=useState<FinancialSettings>({taxPercent:1,advertisingPercent:0,marketplaceCommissionFallbackPercent:0,payoutDelayDays:10,payoutSchedule:'BIWEEKLY',payoutServiceFeePercent:0,urgentWithdrawalFeePercent:2.5}); const [savingSettings,setSavingSettings]=useState(false);const [settingsLoaded,setSettingsLoaded]=useState(false);const [settingsError,setSettingsError]=useState('');
 const columnDefs=[['sku','SKU / товар'],['stock','Остаток'],['price','Цена продажи'],['payout','Выдаётся продавцу'],['payoutTotal','Выплата за весь остаток'],['cost','Товар'],['packaging','Упаковка'],['supply','Доставка поставки'],['additional','Доп. расходы'],['tax','Налог'],['ads','Буст заказов'],['expenses','Все расходы'],['profit','Чистая прибыль']] as const;
 const [hiddenColumns,setHiddenColumns]=useState<string[]>([]);const [columnWidth,setColumnWidth]=useState(120);const [columnsOpen,setColumnsOpen]=useState(false);
 async function load(){setRowsLoading(true);setRowsError('');try{setRows(await api(`/costs?search=${encodeURIComponent(q)}`))}catch(e:any){setRows([]);setRowsError(e.message||'Не удалось загрузить себестоимость SKU')}finally{setRowsLoading(false)}}
 async function loadSupplies(){setSuppliesLoading(true);setSuppliesError('');try{const data=await api<any[]>('/supplies/costing');setSupplies(data);setSupplyCosts(Object.fromEntries(data.map(s=>[s.id,String(s.logisticsCost||0)])))}catch(e:any){setSupplies([]);setSupplyCosts({});setSuppliesError(e.message||'Не удалось загрузить стоимость поставок')}finally{setSuppliesLoading(false)}}
 async function loadSettings(){setSettingsLoaded(false);setSettingsError('');try{setSettings(await api<FinancialSettings>('/costs/settings'));setSettingsLoaded(true)}catch(e:any){setSettingsError(e.message||'Не удалось загрузить финансовые настройки')}}
 useEffect(()=>{void loadSettings()},[]);
 useEffect(()=>{void loadSupplies()},[]);
 useEffect(()=>{const t=setTimeout(()=>void load(),200);return()=>clearTimeout(t)},[q]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('cost-columns')||'{}');setHiddenColumns(saved.hidden||[]);setColumnWidth(saved.width||120)}catch{}},[]);
 useEffect(()=>{document.documentElement.dataset.costHidden=hiddenColumns.join(' ');document.documentElement.style.setProperty('--cost-col-width',`${columnWidth}px`);localStorage.setItem('cost-columns',JSON.stringify({hidden:hiddenColumns,width:columnWidth}))},[hiddenColumns,columnWidth]);
 const missing=rows.filter(r=>!r.cost).length;
 const potential=rows.reduce((sum,r)=>{const stock=Math.max(0,Number(r.stock||0));const productCost=Number(r.cost||0)*stock;const rateKnown=Boolean(r.orderBoostEnabled)&&r.advertisingEstimate!==null;const expenses=Number(r.cost||0)+Number(r.packagingCost||0)+Number(r.warehouseLogisticsCost||0)+Number(r.additionalCost||0)+Number(r.price||0)*settings.taxPercent/100+Number(r.advertisingEstimate||0);sum.units+=stock;sum.sales+=Number(r.price||0)*stock;sum.payout+=Number(r.sellerPayout||0)*stock;sum.productCost+=productCost;sum.expenses+=expenses*stock;sum.profit+=(Number(r.sellerPayout||0)-expenses)*stock;if(!rateKnown)sum.unknownAdvertising+=1;return sum},{units:0,sales:0,payout:0,productCost:0,expenses:0,profit:0,unknownAdvertising:0});
 function update(id:string,key:string,value:string){const number=Number(value)||0;setRows(v=>v.map(r=>{if(r.id!==id)return r;const next={...r,[key]:number};const base=next.cost+next.packagingCost+next.warehouseLogisticsCost+next.additionalCost;next.taxEstimate=next.price*settings.taxPercent/100;const rateKnown=Boolean(next.orderBoostEnabled);next.advertisingEstimate=rateKnown?next.price*Number(next.advertisingPercent??0)/100:null;next.fullCostEstimate=rateKnown?base+next.taxEstimate+Number(next.advertisingEstimate):null;next.marginEstimate=next.fullCostEstimate===null?null:next.sellerPayout-next.fullCostEstimate;next.marginEstimateKnown=rateKnown;return next}));setDirty(d=>({...d,[id]:{...(d[id]||{}),[key]:number}}))}
 async function save(){setSaving(true);try{const items=Object.entries(dirty).map(([skuId,v]:any)=>{const r=rows.find(x=>x.id===skuId);return{skuId,amount:v.cost??r.cost,packagingCost:v.packagingCost??r.packagingCost,warehouseLogisticsCost:v.warehouseLogisticsCost??r.warehouseLogisticsCost,additionalCost:v.additionalCost??r.additionalCost}});await api('/costs/bulk',{method:'POST',body:JSON.stringify({items})});setDirty({});await load()}catch(e:any){alert(e.message)}finally{setSaving(false)}}
 async function saveSettings(){if(!settingsLoaded)return;setSavingSettings(true);setSettingsError('');try{const payload={taxPercent:settings.taxPercent,marketplaceCommissionFallbackPercent:settings.marketplaceCommissionFallbackPercent,payoutDelayDays:settings.payoutDelayDays,payoutSchedule:settings.payoutSchedule,payoutServiceFeePercent:settings.payoutServiceFeePercent,urgentWithdrawalFeePercent:settings.urgentWithdrawalFeePercent};const saved=await api<FinancialSettings>('/costs/settings',{method:'POST',body:JSON.stringify(payload)});setSettings(saved);await load()}catch(e:any){setSettingsError(e.message||'Не удалось сохранить финансовые настройки')}finally{setSavingSettings(false)}}
 async function saveSupply(id:string){setSavingSupply(id);try{await api(`/supplies/${id}/logistics-cost`,{method:'POST',body:JSON.stringify({amount:Number(supplyCosts[id])||0})});await Promise.all([loadSupplies(),load()])}catch(e:any){alert(e.message)}finally{setSavingSupply('')}}
 function exportCsv(){const csv=['SKU;Штрихкод;Товар;Цвет;Размер;Себестоимость;Упаковка;Логистика до склада;Доп. расходы',...rows.map(r=>[r.sellerSku||'',r.barcode||'',`"${r.product.replaceAll('"','""')}"`,r.color||'',r.size||'',r.cost,r.packagingCost,r.warehouseLogisticsCost,r.additionalCost].join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='uzum-costs.csv';a.click();URL.revokeObjectURL(a.href)}
 async function importCsv(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const lines=(await f.text()).split(/\r?\n/).slice(1);for(const line of lines){if(!line.trim())continue;const cols=line.split(';');const sku=cols[0];const row=rows.find(r=>r.sellerSku===sku);if(row){update(row.id,'cost',cols[5]||'0');update(row.id,'packagingCost',cols[6]||'0');update(row.id,'warehouseLogisticsCost',cols[7]||'0');update(row.id,'additionalCost',cols[8]||'0')}}e.target.value=''}
 return <AppShell periodEnabled={false} title="Себестоимость" subtitle="Полная стоимость SKU и расчёт прибыли по наблюдаемым ставкам налога и рекламы">
  {rowsError?<div className="error-box settings-notice"><span>{rowsError}</span><button className="ghost" onClick={()=>void load()}>Повторить</button></div>:rowsLoading?<div className="loading">Загружаем себестоимость SKU…</div>:<div className="cost-potential"><div><span>ТЕКУЩИЙ ОСТАТОК</span><b>{potential.units} шт.</b></div><div><span>ПОТЕНЦИАЛЬНЫЕ ПРОДАЖИ</span><b>{money(potential.sales)}</b></div><div><span>ПОТЕНЦИАЛЬНАЯ ВЫПЛАТА UZUM</span><b>{money(potential.payout)}</b></div><div><span>СЕБЕСТОИМОСТЬ ВСЕХ ТОВАРОВ</span><b>{money(potential.productCost)}</b></div><div><span>ВСЕ РАСХОДЫ</span><b>{potential.unknownAdvertising?'неполный расчёт':money(potential.expenses)}</b></div><div><span>ПОТЕНЦИАЛЬНАЯ ПРИБЫЛЬ</span><b className={!potential.unknownAdvertising&&potential.profit>=0?'positive':'negative'}>{potential.unknownAdvertising?`нет ставки у ${potential.unknownAdvertising} SKU`:money(potential.profit)}</b></div></div>}
  <div className="cost-column-settings"><button className="ghost" onClick={()=>setColumnsOpen(v=>!v)}><SlidersHorizontal size={16}/>Настроить таблицу</button><label>Ширина колонок <input type="range" min="80" max="260" step="10" value={columnWidth} onChange={e=>setColumnWidth(Number(e.target.value))}/><b>{columnWidth}px</b></label>{columnsOpen&&<div className="cost-column-picker">{columnDefs.map(([key,label])=><label key={key}><input type="checkbox" checked={!hiddenColumns.includes(key)} onChange={()=>setHiddenColumns(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])}/>{label}</label>)}</div>}</div>
  <div className="finance-settings-banner"><div className="finance-settings-copy"><Calculator size={22}/><div><b>Расходы после выплаты Uzum</b><span>Комиссия МП и логистика Uzum уже вычтены из «выдаётся продавцу» и повторно не списываются.</span></div></div><label>Налог<input disabled={!settingsLoaded||savingSettings} type="number" min="0" max="100" step="0.1" value={settings.taxPercent} onChange={e=>setSettings({...settings,taxPercent:Number(e.target.value)||0})}/><b>%</b></label><label>Удержание до корзины<input disabled={!settingsLoaded||savingSettings} type="number" min="0" max="90" step="1" value={settings.payoutDelayDays} onChange={e=>setSettings({...settings,payoutDelayDays:Math.max(0,Math.min(90,Math.trunc(Number(e.target.value)||0)))})}/><b>дн.</b></label><label>График выплат<select disabled={!settingsLoaded||savingSettings} value={settings.payoutSchedule} onChange={e=>setSettings({...settings,payoutSchedule:e.target.value})}><option value="DAILY">Каждый рабочий день</option><option value="WEEKLY">Еженедельно</option><option value="BIWEEKLY">Раз в 2 недели</option><option value="MONTHLY">Раз в месяц</option></select></label><label>Плата вывода<input disabled={!settingsLoaded||savingSettings} type="number" min="0" max="10" step="0.1" value={settings.payoutServiceFeePercent} onChange={e=>setSettings({...settings,payoutServiceFeePercent:Number(e.target.value)||0})}/><b>%</b></label><button className="primary" onClick={saveSettings} disabled={!settingsLoaded||savingSettings}><Save size={16}/>{savingSettings?'Сохраняем…':settingsLoaded?'Сохранить настройки':'Загрузка настроек…'}</button></div>
  {settingsError&&<div className="error-box settings-notice">{settingsError} <button className="ghost" onClick={()=>void loadSettings()}>Повторить</button></div>}
  <div className="cost-formula"><b>Чистая прибыль =</b><span>выдаётся продавцу</span><i>−</i><span>товар</span><i>−</i><span>упаковка</span><i>−</i><span>доставка поставки / количество</span><i>−</i><span>доп. расходы</span><i>−</i><span>{settings.taxPercent}% налог</span><i>−</i><span>оценка рекламы по последней ставке товара</span></div><div className="payout-setting-note">Для каждого товара используется только его последняя фактическая ставка буста из Uzum. Если подтверждённой ставки нет, система не подставляет 0%: рекламный расход и итоговая прибыль SKU остаются неизвестными. Ручная общая ставка не применяется.</div>
  {suppliesError?<div className="error-box settings-notice"><span>{suppliesError}</span><button className="ghost" onClick={()=>void loadSupplies()}>Повторить</button></div>:suppliesLoading?<div className="loading">Загружаем стоимость поставок…</div>:<section className="panel supply-costing"><div className="panel-head"><div><h2><Truck size={18}/> Доставка поставок до склада Uzum</h2><p>Введите полную сумму доставки. Состав и количество SKU берутся из накладной Uzum, сумма автоматически делится на единицы.</p></div></div><div className="modern-table"><div className="modern-row head"><span>Поставка</span><span>Статус</span><span>SKU</span><span>Единиц</span><span>Сумма доставки</span><span>На единицу</span><span></span></div>{supplies.map(s=><div className="modern-row" key={s.id}><b>№ {s.externalId}</b><span>{s.statusLabel||s.status}</span><span>{s.itemCount||'—'}</span><span>{s.units||'—'}</span><span><input className="cell-input" type="number" min="0" value={supplyCosts[s.id]??'0'} onChange={e=>setSupplyCosts(v=>({...v,[s.id]:e.target.value}))}/></span><span>{money(s.costPerUnit||0)}</span><button className="ghost" onClick={()=>saveSupply(s.id)} disabled={savingSupply===s.id}>{savingSupply===s.id?'Сохраняем…':'Распределить'}</button></div>)}</div></section>}
  {!rowsLoading&&!rowsError&&<><div className="toolbar"><div className="search grow"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск по товару, SKU или штрихкоду"/></div><span className="counter">Товаров: {new Set(rows.map(r=>r.product)).size} • SKU: {rows.length} • Без себестоимости: {missing}</span><button className="ghost" onClick={exportCsv}><Download size={16}/>Экспорт CSV</button><label className="button ghost"><Upload size={16}/>Импорт CSV<input hidden type="file" accept=".csv" onChange={importCsv}/></label><button className="primary" disabled={!Object.keys(dirty).length||saving} onClick={save}><Save size={16}/>{saving?'Сохраняем…':`Сохранить (${Object.keys(dirty).length})`}</button></div>
  <section className="panel table-panel"><table className="cost-table"><thead><tr><th>SKU / ТОВАР</th><th>ОСТАТОК</th><th>ЦЕНА ПРОДАЖИ</th><th>ВЫДАЁТСЯ ПРОДАВЦУ / ШТ.</th><th>ВЫПЛАТА ЗА ВЕСЬ ОСТАТОК</th><th>ТОВАР</th><th>УПАКОВКА</th><th>ДОСТАВКА ПОСТАВКИ / ШТ.</th><th>ДОП. РАСХОДЫ</th><th>НАЛОГ {settings.taxPercent}%</th><th>БУСТ ЗАКАЗОВ*</th><th>РАСХОДЫ ПОСЛЕ ВЫПЛАТЫ</th><th>ЧИСТАЯ ПРИБЫЛЬ</th></tr></thead><tbody>{rows.map(r=>{const ads=r.advertisingEstimate===null?null:Number(r.advertisingEstimate);const expenses=r.cost+r.packagingCost+r.warehouseLogisticsCost+r.additionalCost+r.price*settings.taxPercent/100+Number(ads||0);const profit=r.sellerPayout-expenses;const observedAt=r.advertisingObservedAt?new Date(r.advertisingObservedAt).toLocaleDateString('ru-RU',{timeZone:'Asia/Tashkent'}):null;return <tr key={r.id}><td><b>{r.product}</b><span>{r.sellerSku||'Без артикула'}{r.barcode?` • ${r.barcode}`:''}</span></td><td>{r.stock}</td><td>{money(r.price)}</td><td><b>{money(r.sellerPayout)}</b></td><td><b>{money(r.sellerPayoutTotal)}</b><span>{r.stock} шт. × {money(r.sellerPayout)}</span></td><td><input className="cell-input" type="number" value={r.cost} onChange={e=>update(r.id,'cost',e.target.value)}/></td><td><input className="cell-input" type="number" value={r.packagingCost} onChange={e=>update(r.id,'packagingCost',e.target.value)}/></td><td><b>{money(r.warehouseLogisticsCost)}</b><span>{r.logisticsFromSupplies?'из поставок':'ручное значение'}</span></td><td><input className="cell-input" type="number" value={r.additionalCost} onChange={e=>update(r.id,'additionalCost',e.target.value)}/></td><td>{money(r.price*settings.taxPercent/100)}</td><td><b>{ads===null?'—':money(ads)}</b><span>{r.orderBoostEnabled?`${Number(r.advertisingPercent??0).toFixed(1)}% • последняя ставка товара${observedAt?` от ${observedAt}`:''}`:'нет подтверждённой ставки — 0% не подставляется, итог неизвестен'}</span></td><td><b>{ads===null?'—':money(expenses)}</b></td><td><b className={ads!==null&&profit>0?'positive':'negative'}>{ads===null?'—':money(profit)}</b></td></tr>})}</tbody></table></section></>}
 </AppShell>
}
