"use client";
import { useEffect, useState } from 'react';
import { Bot, CheckCircle2, Eye, EyeOff, KeyRound, MessageSquareText, RefreshCw, Save, Send, ShieldCheck, Store } from 'lucide-react';
import AppShell from './AppShell';
import { api } from '@/lib/api';
import { Status } from './UI';

type TelegramForm={token:string;chatId:string;dailyDigestTime:string;notifyDailyDigest:boolean;notifyNewOrders:boolean;notifyLowStock:boolean;notifyGoals:boolean;notifyErrors:boolean;notifySupplyStatus:boolean;notifySlotFound:boolean};

export default function SettingsClient(){
 const [items,setItems]=useState<any[]>([]);
 const [uzum,setUzum]=useState({token:'',shopId:'',shopName:''});
 const [uzumInternalToken,setUzumInternalToken]=useState('');
 const [claude,setClaude]=useState({token:'',provider:'openclaw',model:'claude-opus-5',openclawModel:'',autoReplyEnabled:false});
 const [tg,setTg]=useState<TelegramForm>({token:'',chatId:'',dailyDigestTime:'09:00',notifyDailyDigest:true,notifyNewOrders:true,notifyLowStock:true,notifyGoals:true,notifyErrors:true,notifySupplyStatus:true,notifySlotFound:true});
 const [show,setShow]=useState({u:false,i:false,o:false,t:false});const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [loaded,setLoaded]=useState(false);
 const load=()=>api<any[]>('/integrations').then(v=>{setItems(v);const t=v.find(x=>x.type==='TELEGRAM');if(t?.metadata)setTg(x=>({...x,...t.metadata}));const u=v.find(x=>x.type==='UZUM');if(u?.metadata)setUzum(x=>({...x,shopId:u.metadata.shopId||'',shopName:u.metadata.shopName||''}));const o=v.find(x=>x.type==='ANTHROPIC');if(o?.metadata)setClaude(x=>({...x,provider:o.metadata.provider==='api'?'api':'openclaw',model:o.metadata.model||x.model,openclawModel:o.metadata.openclawModel||'',autoReplyEnabled:Boolean(o.metadata.autoReplyEnabled)}))}).catch((e:Error)=>setNotice(`Ошибка: ${e.message}`)).finally(()=>setLoaded(true));
 useEffect(()=>{load()},[]);const row=(type:string)=>items.find(x=>x.type===type);
 async function act(type:string,action:'save'|'test'){
  if(!loaded){setNotice('Ошибка: настройки ещё не загружены');return}
  setBusy(type+action);setNotice('');
  try{const data=type==='UZUM'?uzum:type==='UZUM_INTERNAL'?{token:uzumInternalToken,shopId:uzum.shopId}:type==='ANTHROPIC'?claude:tg;const path=action==='save'?`/integrations/${type}`:`/integrations/${type}/test`;const result:any=await api(path,{method:action==='save'?'PUT':'POST',body:JSON.stringify(data)});await load();if(action==='save'&&type==='UZUM_INTERNAL'){setUzumInternalToken('');setShow(x=>({...x,i:false}))}setNotice(action==='save'?'Настройки сохранены':type==='TELEGRAM'?`Тестовое сообщение доставлено. Message ID: ${result.details?.messageId||'—'}`:type==='UZUM_INTERNAL'?'Токен для синхронизации отзывов проверен':type==='ANTHROPIC'?(claude.provider==='api'?'API Anthropic подключён':`OpenClaw отвечает: ${result.details?.answer||'ok'}`):'Uzum API и Shop ID проверены');}
  catch(e:any){setNotice(`Ошибка: ${e.message}`)}finally{setBusy('')}
 }
 const toggle=(key:keyof TelegramForm)=>(e:React.ChangeEvent<HTMLInputElement>)=>setTg({...tg,[key]:e.target.checked});
 return <AppShell periodEnabled={false} title="Настройки" subtitle="Безопасное подключение Uzum API и реальная проверка доставки Telegram">
  {notice&&<div className={notice.startsWith('Ошибка')?'error-box settings-notice':'success-box settings-notice'}>{notice}</div>}
  <div className="settings-grid">
   <section className="integration-card"><div className="integration-head"><div className="integration-icon uz"><Store/></div><div><h2>Uzum Seller API</h2><p>Магазины, товары, SKU, заказы и остатки</p></div><Status tone={row('UZUM')?.status==='CONNECTED'?'green':row('UZUM')?.status==='ERROR'?'red':'gray'}>{row('UZUM')?.status==='CONNECTED'?'Подключено':row('UZUM')?.status==='ERROR'?'Ошибка':'Не настроено'}</Status></div>
    <label>API token<div className="secret-input"><KeyRound size={17}/><input type={show.u?'text':'password'} value={uzum.token} onChange={e=>setUzum({...uzum,token:e.target.value})} placeholder={row('UZUM')?.tokenMasked||'Вставьте новый токен'}/><button type="button" onClick={()=>setShow({...show,u:!show.u})}>{show.u?<EyeOff/>:<Eye/>}</button></div><small>После сохранения токен показывается только маской.</small></label>
    <div className="form-row"><label>Shop ID<input value={uzum.shopId} onChange={e=>setUzum({...uzum,shopId:e.target.value})}/></label><label>Название магазина<input value={uzum.shopName} onChange={e=>setUzum({...uzum,shopName:e.target.value})}/></label></div>
   {row('UZUM')?.lastError&&<div className="error-box">{row('UZUM').lastError}</div>}<div className="card-actions"><button className="ghost" disabled={busy!==''} onClick={()=>act('UZUM','test')}><RefreshCw size={16}/>Проверить API</button><button className="primary" disabled={busy!==''} onClick={()=>act('UZUM','save')}><Save size={16}/>Сохранить</button></div>
   </section>
   <section className="integration-card"><div className="integration-head"><div className="integration-icon uz"><MessageSquareText/></div><div><h2>Отзывы Uzum</h2><p>Токен кабинета для синхронизации отзывов только на чтение</p></div><Status tone={row('UZUM_INTERNAL')?.status==='CONNECTED'?'green':row('UZUM_INTERNAL')?.status==='ERROR'?'red':'gray'}>{row('UZUM_INTERNAL')?.status==='CONNECTED'?'Подключено':row('UZUM_INTERNAL')?.status==='ERROR'?'Ошибка':'Не настроено'}</Status></div>
    <label>Bearer token кабинета Uzum<div className="secret-input"><KeyRound size={17}/><input type={show.i?'text':'password'} value={uzumInternalToken} onChange={e=>setUzumInternalToken(e.target.value)} placeholder={row('UZUM_INTERNAL')?.tokenMasked?'Токен сохранён — вставьте новый для замены':'Вставьте Bearer token'}/><button type="button" onClick={()=>setShow({...show,i:!show.i})}>{show.i?<EyeOff/>:<Eye/>}</button></div><small>Токен используется только для чтения и синхронизации отзывов. Сохранённое значение никогда не показывается.</small></label>
    <label>Shop ID<input value={uzum.shopId} disabled/><small>Используется Shop ID из настроек Uzum Seller API выше.</small></label>
    {row('UZUM_INTERNAL')?.lastError&&<div className="error-box">{row('UZUM_INTERNAL').lastError}</div>}<div className="card-actions"><button className="ghost" disabled={busy!==''} onClick={()=>act('UZUM_INTERNAL','test')}><RefreshCw size={16}/>Проверить доступ</button><button className="primary" disabled={busy!==''} onClick={()=>act('UZUM_INTERNAL','save')}><Save size={16}/>Сохранить</button></div>
   </section>
   <section className="integration-card"><div className="integration-head"><div className="integration-icon uz"><Bot/></div><div><h2>AI-ответы Claude</h2><p>Черновики ответов на русском и узбекском языке</p></div><Status tone={row('ANTHROPIC')?.status==='CONNECTED'?'green':row('ANTHROPIC')?.status==='ERROR'?'red':'gray'}>{row('ANTHROPIC')?.status==='CONNECTED'?'Подключено':row('ANTHROPIC')?.status==='ERROR'?'Ошибка':'Не настроено'}</Status></div><label>Чем генерировать<select value={claude.provider} onChange={e=>setClaude({...claude,provider:e.target.value})}><option value="openclaw">OpenClaw на сервере — без ключа</option><option value="api">API Anthropic — по ключу</option></select></label>{claude.provider==='openclaw'?<><label>Модель OpenClaw — можно оставить пустым<input value={claude.openclawModel} onChange={e=>setClaude({...claude,openclawModel:e.target.value})} placeholder="claude-cli/claude-sonnet-5"/></label><small>Ответы пишет OpenClaw, уже установленный на этом сервере — тот же, что ведёт Telegram-ботов фабрики. Ключ и оплата не нужны, ничего секретного в базе не хранится. Пустое поле — модель агента по умолчанию.</small></>:<><label>Anthropic API key — необязательно<div className="secret-input"><KeyRound size={17}/><input type={show.o?'text':'password'} value={claude.token} onChange={e=>setClaude({...claude,token:e.target.value})} placeholder={row('ANTHROPIC')?.tokenMasked||'sk-ant-…'}/><button type="button" onClick={()=>setShow({...show,o:!show.o})}>{show.o?<EyeOff/>:<Eye/>}</button></div></label><label>Модель<input value={claude.model} onChange={e=>setClaude({...claude,model:e.target.value})}/></label><small>Запросы идут на api.anthropic.com и оплачиваются по расходу. Пустой ключ — тогда берутся учётные данные самого сервера.</small></>}<div className="notify-grid"><label><input type="checkbox" checked={claude.autoReplyEnabled} onChange={e=>setClaude({...claude,autoReplyEnabled:e.target.checked})}/> Автоматически отправлять безопасные ответы на отзывы 4–5★</label></div><small>Отзывы 1–3★ и жалобы никогда не отправляются автоматически.</small>{row('ANTHROPIC')?.lastError&&<div className="error-box">{row('ANTHROPIC').lastError}</div>}<div className="card-actions"><button className="ghost" disabled={busy!==''} onClick={()=>act('ANTHROPIC','test')}><RefreshCw size={16}/>Проверить</button><button className="primary" disabled={busy!==''} onClick={()=>act('ANTHROPIC','save')}><Save size={16}/>Сохранить</button></div></section>
   <section className="integration-card"><div className="integration-head"><div className="integration-icon tg"><Bot/></div><div><h2>Telegram-бот</h2><p>Проверка включает getMe и реальную отправку сообщения</p></div><Status tone={row('TELEGRAM')?.status==='CONNECTED'?'green':row('TELEGRAM')?.status==='ERROR'?'red':'gray'}>{row('TELEGRAM')?.status==='CONNECTED'?'Подключено':row('TELEGRAM')?.status==='ERROR'?'Ошибка':'Не настроено'}</Status></div>
    <label>Bot token<div className="secret-input"><KeyRound size={17}/><input type={show.t?'text':'password'} value={tg.token} onChange={e=>setTg({...tg,token:e.target.value})} placeholder={row('TELEGRAM')?.tokenMasked||'123456:ABC…'}/><button type="button" onClick={()=>setShow({...show,t:!show.t})}>{show.t?<EyeOff/>:<Eye/>}</button></div></label>
    <label>Chat ID<div className="secret-input"><Send size={17}/><input value={tg.chatId} onChange={e=>setTg({...tg,chatId:e.target.value})} placeholder="Например: -1001234567890"/></div><small>Сначала напишите боту /start или добавьте его в группу.</small></label>
    <div className="form-row"><label>Время ежедневного отчёта<input type="time" value={tg.dailyDigestTime} onChange={e=>setTg({...tg,dailyDigestTime:e.target.value})}/></label><label>Часовой пояс<input value="Asia/Tashkent" disabled/></label></div>
    <div className="notify-grid"><label><input type="checkbox" checked={tg.notifyDailyDigest} onChange={toggle('notifyDailyDigest')}/> Ежедневный отчёт</label><label><input type="checkbox" checked={tg.notifyNewOrders} onChange={toggle('notifyNewOrders')}/> Новые заказы и отмены</label><label><input type="checkbox" checked={tg.notifyLowStock} onChange={toggle('notifyLowStock')}/> Низкие остатки</label><label><input type="checkbox" checked={tg.notifyGoals} onChange={toggle('notifyGoals')}/> Выполнение целей</label><label><input type="checkbox" checked={tg.notifyErrors} onChange={toggle('notifyErrors')}/> Ошибки синхронизации</label><label><input type="checkbox" checked={tg.notifySupplyStatus} onChange={toggle('notifySupplyStatus')}/> Смена статуса поставок</label><label><input type="checkbox" checked={tg.notifySlotFound} onChange={toggle('notifySlotFound')}/> Найден тайм-слот</label></div>
    {row('TELEGRAM')?.lastError&&<div className="error-box">{row('TELEGRAM').lastError}</div>}<div className="card-actions"><button className="ghost" disabled={busy!==''} onClick={()=>act('TELEGRAM','test')}><RefreshCw size={16}/>Отправить тест</button><button className="primary" disabled={busy!==''} onClick={()=>act('TELEGRAM','save')}><Save size={16}/>Сохранить</button></div>
   </section>
  </div>
  <section className="panel security-panel"><div><ShieldCheck/><div><h2>Как хранятся секреты</h2><p>Токены шифруются AES-256-GCM. Ключ шифрования хранится только в переменной окружения сервера.</p></div></div><CheckCircle2/></section>
 </AppShell>
}
