"use client";
import { ChangeEvent, useEffect, useState } from 'react';
import { AlertTriangle, Boxes, FileSpreadsheet, PackagePlus, RefreshCw, Search, ShieldAlert, TrendingUp, Upload } from 'lucide-react';
import AppShell from './AppShell';
import { api, apiForm, money } from '@/lib/api';
import { Status } from './UI';

export default function WarehouseClient(){
 const [data,setData]=useState<any>(null);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const load=()=>api(`/warehouse/overview?search=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`).then(setData).catch(e=>setMessage(e.message));
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q,status]);
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage('');try{const form=new FormData();form.append('file',file);const r:any=await apiForm('/warehouse/import',form);setMessage(r.duplicate?`Этот отчёт уже загружен (${r.rows} строк)`:`Импортировано ${r.rows} SKU, сопоставлено ${r.matchedSkus}`);await load()}catch(err:any){setMessage(`Ошибка: ${err.message}`)}finally{setBusy(false);e.target.value=''}}
 const s=data?.summary;
 return <AppShell periodEnabled={false} title="Склад и потенциал" subtitle="Импорт отчёта Uzum «Остатки (новый)»: целевой запас, поставка, потенциальная выплата и прибыль">
  <div className="warehouse-upload"><div><FileSpreadsheet/><div><b>Загрузите отчёт .xlsx из Uzum</b><span>Повторный файл определяется по SHA-256 и не дублируется</span></div></div><label className="primary"><Upload size={16}/>{busy?'Импорт…':'Импортировать Excel'}<input hidden type="file" accept=".xlsx" disabled={busy} onChange={upload}/></label></div>
  {message&&<div className={message.startsWith('Ошибка')?'error-box settings-notice':'success-box settings-notice'}>{message}</div>}
  {data?.empty?<section className="empty-state"><Boxes/><h2>Отчёт ещё не загружен</h2><p>{data.message}</p></section>:data&&<>
   <div className="warehouse-report-meta"><span>Отчёт: <b>{data.report.fileName}</b></span><span>На дату: <b>{data.report.reportAsOf?new Date(data.report.reportAsOf).toLocaleString('ru-RU',{timeZone:'Asia/Tashkent'}):'не указана'}</b></span><span>Импорт: <b>{new Date(data.report.importedAt).toLocaleString('ru-RU',{timeZone:'Asia/Tashkent'})}</b></span></div>
   <div className="warehouse-kpis"><div><Boxes/><span>НА СКЛАДЕ МП</span><b>{s.marketplaceTotal} шт.</b><small>Доступно {s.availableForSale} · {s.sellableShare.toFixed(1)}%</small></div><div><PackagePlus/><span>НУЖНО ДОВЕЗТИ</span><b>{s.recommendedSupply} шт.</b><small>{s.supplySkus} SKU</small></div><div><TrendingUp/><span>ЦЕЛЕВОЙ ЗАПАС</span><b>{s.targetMarketplaceStock} шт.</b><small>текущий + рекомендация</small></div><div><AlertTriangle/><span>ЗАКАНЧИВАЮТСЯ</span><b>{s.endingSoonSkus} SKU</b><small>медианный запас {s.medianCoverageDays.toFixed(0)} дней</small></div><div><ShieldAlert/><span>ВОЗВРАТЫ / БРАК</span><b>{s.fromCustomer} / {s.defective}</b><small>{s.returnShare.toFixed(1)}% / {s.defectShare.toFixed(1)}%</small></div><div><TrendingUp/><span>ПОТЕНЦИАЛЬНАЯ ВЫПЛАТА</span><b>{money(s.potentialPayout)}</b><small>по данным Uzum</small></div><div><TrendingUp/><span>ИЗВЕСТНАЯ ПОТЕНЦ. ПРИБЫЛЬ</span><b>{money(s.potentialNetProfit)}</b><small>покрытие расчёта {s.potentialProfitCoverage.toFixed(0)}%</small></div><div><Boxes/><span>СТОИМОСТЬ ЗАПАСА</span><b>{money(s.stockCost)}</b><small>{s.rowsWithoutCost} строк без себестоимости</small></div></div>
   <section className="panel warehouse-insights"><div className="panel-head"><div><h2>Полезные метрики для решений</h2><p>Расчёт на основе отчёта Uzum, текущих цен, себестоимости и наблюдаемых ставок рекламы</p></div><Status tone={s.advertisingRateCoverage>=99.9?'green':'amber'}>Ставки рекламы: {s.advertisingRateCoverage.toFixed(0)}% SKU</Status></div><div className="warehouse-decision-grid"><div><span>ИНВЕСТИЦИЯ В РЕКОМЕНДОВАННУЮ ПОСТАВКУ</span><b>{money(s.supplyInvestment)}</b><small>по полной себестоимости с логистикой до склада</small></div><div><span>ИЗВЕСТНАЯ ПРИБЫЛЬ ПО НОВОЙ ПОСТАВКЕ</span><b>{money(s.recommendedPotentialProfit)}</b><small>налог {Number(data.financialSettings?.taxPercent??0)}%; неизвестные ставки рекламы исключены, а не заменены нулём</small></div><div><span>КАПИТАЛ В ИЗБЫТОЧНЫХ ОСТАТКАХ</span><b>{money(s.frozenOverstockCapital)}</b><small>{s.overstockSkus} SKU с избытком</small></div><div><span>ВЫПЛАТА ПОД РИСКОМ ИЗ-ЗА ДЕФИЦИТА</span><b>{money(s.atRiskPayout)}</b><small>{s.endingSoonSkus} заканчивающихся SKU</small></div><div><span>ПОКРЫТИЕ РАСЧЁТА ПРИБЫЛИ</span><b>{s.potentialProfitCoverage.toFixed(0)}%</b><small>{s.rowsWithoutCost} без себестоимости, {s.rowsWithoutPrice} без цены или ставки</small></div><div><span>SKU С ОТРИЦАТЕЛЬНОЙ ВЫПЛАТОЙ</span><b>{s.negativePayoutSkus}</b><small>нужно проверить цену и удержания</small></div><div><span>ROI РЕКОМЕНДОВАННОЙ ПОСТАВКИ</span><b>{s.recommendedSupplyRoi.toFixed(1)}%</b><small>только строки с полными исходными данными</small></div><div><span>ЕДИНИЦ НЕ В СВОБОДНОЙ ПРОДАЖЕ</span><b>{s.blockedUnits} шт.</b><small>поставка, логистика, возвраты, СДХ, фотостудия и брак</small></div><div><span>КАПИТАЛ В ВОЗВРАТАХ / БРАКЕ / СДХ</span><b>{money(s.nonSellableCapital)}</b><small>оценка по полной себестоимости</small></div></div></section>
   <div className="toolbar warehouse-toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск SKU, штрихкода, товара…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все статусы</option><option value="SUPPLY">Нужна поставка</option><option value="ENDING">Заканчивается</option><option value="OVERSTOCK">Избыток</option><option value="DEFECT">Есть брак</option><option value="NEGATIVE">Отрицательная выплата</option></select><button className="ghost" onClick={load}><RefreshCw size={16}/>Обновить</button></div>
   <section className="panel warehouse-table-wrap"><table className="warehouse-table"><thead><tr><th>Товар / SKU</th><th>Запас дней</th><th>Сейчас МП</th><th>Доступно</th><th>К клиенту</th><th>Возврат</th><th>Довезти</th><th>Должно быть</th><th>Реклама</th><th>Потенц. выплата</th><th>Потенц. прибыль</th><th>ROI запаса</th></tr></thead><tbody>{data.rows.map((r:any)=><tr key={r.id} className={r.endingSoon?'urgent':''}><td><b>{r.productTitle}</b><span>{r.sellerSku}{!r.skuMatched?' • не сопоставлен':''}{!r.hasCost?' • нет себестоимости':''}</span></td><td><b>{r.coverageDays}</b><span>{r.coverageIndicator||'—'}</span></td><td>{r.marketplaceTotal}</td><td>{r.availableForSale}</td><td>{r.toCustomer}</td><td>{r.fromCustomer}</td><td><Status tone={r.recommendedSupply>0?'amber':'gray'}>{r.recommendedSupply}</Status></td><td><b>{r.targetMarketplaceStock}</b></td><td><b>{r.advertisingRateKnown?`${Number(r.advertisingPercent??0).toFixed(1)}%`:'—'}</b><span>{r.advertisingRateKnown?'последняя ставка товара':'нет подтверждённой ставки'}</span></td><td>{money(r.potentialPayoutTotal)}</td><td className={r.potentialNetProfitKnown&&r.potentialNetProfit>=0?'positive':'negative'}>{r.potentialNetProfitKnown?money(r.potentialNetProfit):'нет цены, себестоимости или ставки'}</td><td>{r.potentialNetProfitKnown&&r.potentialStockRoi!==null?`${r.potentialStockRoi.toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></section>
  </>}
 </AppShell>
}
